### PR TITLE
fix: experiement_results migration

### LINKED ISSUE #111: feat: result table crud
result_tbl 
-uuid
-course_id
_experiment_id
-result_data json(3000)
-time_started varchar(10)
-time_submited varchar(10)
-time_left varchar(10)
-status => [not started, started, completed]

@bynalab , @Auwalms

### LINKED ISSUE #112: fix: save_experiment_result endpoint
please let this endpoint update as well create. so if result exist it should update else it should create. 
@bynalab @Auwalms

### PR DESCRIPTION
**Pull request by bynalab**
resolve #111 
resolve #112

### CODE REVIEW

File: app/Http/Controllers/Api/ExperimentController.php [hunk 1]
```diff
@@ -188,22 +189,44 @@ public function saveExperimentResult(Request $request)
         $experimentResult = new ExperimentResult();
 
         $experimentId = $request->get('experiment_id');
+        $timeStarted = $request->get('time_started');
```
Comment (Auwalms) [inline app/Http/Controllers/Api/ExperimentController.php:192]: You missed course_id  in the addition, please add in.

**Review by Auwalms — CHANGES_REQUESTED** [review]
Great job @bynalab, however you missed course_id field in the db column.

File: app/Http/Controllers/Api/ExperimentController.php (hunk 1 above)
Comment (bynalab) [reply app/Http/Controllers/Api/ExperimentController.php:192]: To avoid redundancy, there is experiment_id and experiment belong to a course, I can trace back to get course_id that way. Don't you think?

File: app/Http/Controllers/Api/CourseController.php [hunk 2]
```diff
@@ -262,6 +262,32 @@ public function bulkCourseAssign(Request $request)
         }
     }
 
+    public function enrollStudent(Request $request)
+    {
+        $validator = Validator::make($request->all(), [
+            'course_id' => 'required',
+            'enrollment_code' => 'required',
```
Comment (Auwalms) [inline app/Http/Controllers/Api/CourseController.php]: The enrollment code isn't required for IBBUL students, it's only needed for Baze University Students. You may want to remove it here.

File: app/Http/Controllers/Api/ExperimentController.php (hunk 1 above)
Comment (Auwalms) [reply app/Http/Controllers/Api/ExperimentController.php:192]: @bynalab I think he has a need for Course ID on the Frontend but let's hear from the horse's mouth. @saidabdul80 thoughts?

Comment (saidabdul80) [reply app/Http/Controllers/Api/ExperimentController.php:192]: Yes sir, so he can return course_id since there's a relationship between both

File: app/Http/Controllers/Api/CourseController.php (hunk 2 above)
Comment (saidabdul80) [reply app/Http/Controllers/Api/CourseController.php]: Yes sir, please should not be required, u can just enroll by user_id and course_id

**Comment by saidabdul80** [comment]
Enrollment should be done by user_id and course_id required only.
@Auwalms  He knows how he will return the the course_id

**Review by saidabdul80 — APPROVED** [review]
Good

**Review by Auwalms — APPROVED** [review]
