### PR TITLE
fix: weekly_work to return work_experiments and resolve #126

### LINKED ISSUE #126: feat: user CRUD endpoint
enpoints to create, delete, update individual user as well as read i.e get all users

### PR DESCRIPTION
**Pull request by bynalab**

### CODE REVIEW

File: app/Http/Controllers/Api/UserController.php [hunk 1]
```diff
@@ -25,9 +27,135 @@ public function __construct()
...
+
+        if (empty($checkDuplicate)) {
+            $user->id = $id;
+            $user->username = $user->email = $email;
+            $user->password = $password;
+            $user->first_name = $first_name;
+            $user->other_names = $other_names;
+            $user->gender = $gender;
+            $user->user_ip_address = $user_ip_address;
+            $user->role_id = $this->roleId['faculty_admin'];
```
Comment (Auwalms) [inline app/Http/Controllers/Api/UserController.php:69]: Are we sure all users uploaded here are faculty admins @bynalab ? @saidabdul80 please confirm.

File: app/Http/Controllers/Api/Util.php [hunk 2]
```diff
@@ -7,6 +7,12 @@
 
 class Util extends Controller
 {
+    static public $roleId = [
```
Comment (Auwalms) [inline app/Http/Controllers/Api/Util.php:10]: I love this @bynalab

**Review by Auwalms — COMMENTED** [review]
Please share thoughts on the role of users.

File: app/Http/Controllers/Api/UserController.php (hunk 1 above)
Comment (bynalab) [reply app/Http/Controllers/Api/UserController.php:69]: This particular method is for faculty admin, students are uploaded into the system and school admins are manually created from our end. Was that what we agreed on?

Comment (Auwalms) [reply app/Http/Controllers/Api/UserController.php:69]: True..... So they question is, who is performing this action? School Admin?

Comment (saidabdul80) [reply app/Http/Controllers/Api/UserController.php:69]: what i want is create user, please follow the interface pix i attached to see requirment,
this upload csv can have matric number as well.
because as you can see in the picture we have role, meaning student can also be upload @bynalab @Auwalms

File: routes/api.php [hunk 3]
```diff
@@ -40,6 +40,11 @@
         Route::group([
             'prefix' => 'users'
         ], function () {
+            Route::post('students', [UserController::class, 'getStudents']);
```
Comment (saidabdul80) [inline routes/api.php:43]: this is good sir, let have /create endpoint sir
where admin can any user depending on role he select so one endpoin should serve.
However the one you have done will be beneficial when we implement create student from the intructor end
@bynalab @Auwalms

**Review by saidabdul80 — APPROVED** [review]
please see comment

**Review by Auwalms — APPROVED** [review]
Cool
